

# Site Settings
title: 						"Graham Barnard"
email: 						"barnard.graham@gmail.com"
description: 				"Blog about Developer Self Improvement & Salesforce Development"
baseurl: 					""
url: 						"http://grahambarnard.com"
logourl: 					"/assets/img/bloglogo.jpg"		
fa-logo: 					"fa-bookmark-o"
paginate: 					5


# Author Settings
author_name: 				"Graham Barnard"
author_url: 				"http://grahambarnard.com"
author_bio: 				"Senior Salesforce Developer"
author_email: 				"barnard.graham@gmail.com"
author_image: 				"/assets/img/authorimage.jpg"


# Social Settings
twitter_url: 				"https://twitter.com/grahambarnard"
github_url:  				"https://github.com/GrahamBarnard"
instagram_url:  			"https://instagram.com/instagrahambarnard"
linkedin_url:  				"https://ca.linkedin.com/in/barnardgraham"


# Theme Settings
theme_disqus_shortname: 	""
theme_google_comments: 		false
theme_analytics_id: 		""
theme_analytics_domain: 	""
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

