# Site Settings
title: 						"Graham Barnard"
email: 						"barnard.graham@gmail.com"
description: 				"Thougths about Salesforce, Apex, Developer Processes and Everything Else"
baseurl: 					""
# url: 						"http://localhost:4000"
url: 						"http://grahambarnard.com/"
logourl: 					"/assets/img/authorimage.png"		
fa-logo: 					"fa-bookmark-o"
paginate: 					5


# Author Settings
author_name: 				"Graham Barnard"
author_url: 				"http://grahambarnard.com"
author_bio: 				"Senior Salesforce Developer"
author_email: 				"barnard.graham@gmail.com"
author_image: 				"/assets/img/authorimage.png"


# Social Settings
twitter_url: 				"https://twitter.com/grahambarnard"
github_url:  				"https://github.com/GrahamBarnard"
instagram_url:  			""
linkedin_url:  				"https://ca.linkedin.com/in/barnardgraham"


# Theme Settings
theme_disqus_shortname: 	"grahambarnard"
theme_google_comments: 		false
theme_analytics_id: 		"UA-60848038-1"
theme_analytics_domain: 	""
theme_reading_time: 		true
theme_autoload_comments: 	true
theme_always_show_nav: 		true


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

# Gems
gems: [jekyll-paginate]